---
- name: Create the PostMaster User
  user:
    name: postmaster
    comment: PostMaster Service Account

# The deb package handles dependencies on its own
- include: packages.yml
  when: not postmaster_deb_package

- name: Ensure apache is started and runs at startup
  service:
    name: apache2
    state: started
    enabled: yes

- name: Enable the wsgi module for Apache
  apache2_module:
    state: present
    name: wsgi
  notify: restart apache

- name: Create the logs directory
  file:
    path: /opt/postmaster/logs
    state: directory
    owner: postmaster
    group: www-data
    mode: 0775
    recurse: yes

# Disable PostMaster when the user wants a fresh virtualenv
- name: Disable PostMaster while the virtualenv is being reprovisioned
  file:
    path: /etc/apache2/sites-enabled/postmaster.conf
    state: absent
  when: postmaster_clean_virtualenv
  notify: reload apache

- name: Delete the virtualenv directory
  file:
    path: /opt/postmaster/env
    state: absent
  when: postmaster_clean_virtualenv

- name: Create the virtualenv directory
  file:
    path: /opt/postmaster/env
    state: directory
    owner: postmaster
    group: www-data
    mode: 0775
    recurse: yes

- include: source.yml
  when: not postmaster_deb_package and not postmaster_vagrant_install

- name: Install the python dependencies
  pip:
    requirements: /opt/postmaster/git/requirements.txt
    virtualenv: /opt/postmaster/env

- name: Install the python testing dependencies
  pip:
    requirements: /opt/postmaster/git/test-requirements.txt
    virtualenv: /opt/postmaster/env
  when: postmaster_vagrant_install

- name: Configure PostMaster
  template:
    src: opt/postmaster/git/config.py.j2
    dest: /opt/postmaster/git/config.py

# You can't set permissions on synced folders in Vagrant
- name: Set the permissions on the configuration file
  file:
    path: /opt/postmaster/git/config.py
    mode: 0660
    owner: postmaster
    group: www-data
  when: not postmaster_vagrant_install

- name: Migrate the database
  command: /opt/postmaster/env/bin/python /opt/postmaster/git/manage.py upgradedb
  args:
    chdir: /opt/postmaster/git
  when: postmaster_migrate_db

- name: Check whether to create config.py (deb package only)
  stat:
    path: /opt/postmaster/git/config.py
  register: postmaster_config_file
  when: postmaster_deb_package

- include: ssl.yml
  when: postmaster_apache_ssl_cert is defined and postmaster_apache_ssl_key is defined

- name: Check whether to overwrite the Apache virtualhost configuration (deb package only)
  stat:
    path: /etc/apache2/sites-available/postmaster.conf
  register: postmaster_apache_config_file
  when: postmaster_deb_package

# Don't overwrite postmaster.conf when it is from the deb package and it exists
- name: Configure the Apache virtualhost
  template:
    src: etc/apache2/sites-available/postmaster.conf.j2
    dest: /etc/apache2/sites-available/postmaster.conf
    owner: root
    group: root
    mode: 0644
  notify: reload apache
  when: not postmaster_deb_package or (postmaster_deb_package and not postmaster_apache_config_file.state.exists)

- name: Enable the PostMaster virtual host
  file:
    state: link
    src: /etc/apache2/sites-available/postmaster.conf
    dest: /etc/apache2/sites-enabled/postmaster.conf
    owner: root
    group: root
  notify: reload apache
  when: not postmaster_vagrant_install
