---
# This is used so that the next task doesn't always get marked as changed
- name: Update the apt cache
  apt:
    update_cache: true

- name: Install the dependencies
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - python-pip
    - python-dev
    - python-virtualenv
    - apache2
    - libapache2-mod-wsgi
    - libmysqlclient-dev
